### ISSUE TITLE
borrow X repay Y

### ISSUE THREAD

**Issue by 0-3700** [2501babe/adobe#1]
If adobe has multiple pools it looks like one can borrow one mint and repay same amount of different supported mint.

Wrote a quick and dirty test for it https://gist.github.com/0-3700/b38d4acdc148f7c65c6510b393aca012/revisions

**Comment by 2501babe** [comment]
o yes this is smart thinkin, i was focused on the fact that borrowing from multiple pools is blocked and didnt think about a 1:1
