### ISSUE TITLE
Use anchor declared `AccountsCoder.accountDiscriminator`

### ISSUE THREAD

**Issue by acamill** [2501babe/adobe#2]
It's now available through  `export const accountDiscriminator = AccountsCoder.accountDiscriminator;`

In your code you use size 16 but it's actually 8 in their code, IDK I just went crazy until I checked the source hehe

Not sure that's my issue yet, but for sure seems better to reuse their methode

**Comment by 2501babe** [comment]
discriminator is 8 bytes ya? 16 is because im taking from a base16 string
